general:
  device: cpu
  loss_reduction_func: min
  root_path: /Users/avrahamraviv/PycharmProjects/Formal-Verification-of-Object-Detection-master/FVOD/abcrown_dir
  csv_name: instances.csv
  graph_optimizer: Customized('custom_graph_optimizer', 'merge_sign')
  sparse_interm: false
  save_adv_example: true
model:
  input_shape: [1,1,90,90]
  onnx_loader: Customized('custom_model_loader', 'customized_my_loader')
attack:
  pgd_order: before
  pgd_restarts: 50
  pgd_batch_size: 50
  cex_path: ./cex.txt
solver:
  batch_size: 1
  min_batch_size_ratio: 1
  alpha-crown:
    disable_optimization: ['MaxPool']
  beta-crown:
    iteration: 20
    lr_beta: 0.03
  mip:
    parallel_solvers: 8
    solver_threads: 4
    refine_neuron_time_percentage: 0.8
    skip_unsafe: True
bab:
  pruning_in_iteration: False
  sort_domain_interval: 1
  branching:
    method: nonlinear
    candidates: 3
    nonlinear_split:
      num_branches: 2
      method: shortcut
      filter: true
